# Generated by Django 3.2.18 on 2023-05-18 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingproducts',
            name='etc_note',
        ),
        migrations.RemoveField(
            model_name='savingproducts',
            name='join_deny',
        ),
        migrations.RemoveField(
            model_name='savingproducts',
            name='join_member',
        ),
        migrations.RemoveField(
            model_name='savingproducts',
            name='join_way',
        ),
        migrations.RemoveField(
            model_name='savingproducts',
            name='spcl_cnd',
        ),
    ]
