# Generated by Django 3.2.18 on 2023-05-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_auto_20230518_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingoptions',
            name='intr_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='savingoptions',
            name='intr_rate2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='savingoptions',
            name='intr_rate_type_nm',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='savingoptions',
            name='save_trm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='savingproducts',
            name='fin_prdt_nm',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='savingproducts',
            name='kor_co_nm',
            field=models.TextField(default=''),
        ),
    ]
