# Generated by Django 3.2.18 on 2023-05-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0004_alter_savingoptions_intr_rate2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingoptions',
            name='intr_rate',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
